// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbTEgJAOUNYbjTtuwo7gLfLm5UKqNWkkg',
    appId: '1:102132098358:android:95ab0bcf146990ab997f97',
    messagingSenderId: '102132098358',
    projectId: 'fb-chat-stemmone',
    storageBucket: 'fb-chat-stemmone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDG6CbIMxoziuWe3u64_Uz8dVXhYB4UFg',
    appId: '1:102132098358:ios:ffe4085fd7fa0535997f97',
    messagingSenderId: '102132098358',
    projectId: 'fb-chat-stemmone',
    storageBucket: 'fb-chat-stemmone.firebasestorage.app',
    androidClientId: '102132098358-1nci18ujrshu6j3es0q5nb0eja11i6rl.apps.googleusercontent.com',
    iosClientId: '102132098358-h7h2m1i8qhiulbcokfjg4hv50ul4n4kn.apps.googleusercontent.com',
    iosBundleId: 'eu.org.raannakasturi.fbchat',
  );

}